### ISSUE TITLE
CRUD operations to work with jobs and lists of jobs

### ISSUE THREAD

**Issue by hyzhak** [botstory/todo-bot#4]
# [C]reate
- [x] user types list of items like: 
`"eggs, milk and bread"` and should receive list of options: 

```
1) eggs
2) milk
3) bread
```
- [x] like: ➡️  extend https://github.com/botstory/todo-bot/issues/79
```
🍼 молоко
🍖 мясо(батак без кости, если будет. Если нет, то с костью- это окорочок обыкновенный) 3 шт
🧀 сыр плавленый(Biser) 2 шт
🥑 авокадо
Лосось, если будет в Монтефише. Грамм 400 филе
```
- [x] `"new (list/todo)"` add new list of jobs

# [R]ead
- [x] `"list"` show list of jobs for the last list
- [ ] `"todo [<name>]"` or `"[<name>] todo"` show list of jobs ➡️  https://github.com/botstory/todo-bot/issues/81
- [x] `"all"` show list of lists
- [ ] `"have done"` list of done jobs from current list ➡️  https://github.com/botstory/todo-bot/issues/81

# [U]pdate
- [x] `start/stop/done` in context of list of tasks and task details
- [x] `"start last (job/ticket)"`
- [x] `"done last (job/ticket)"` close last job
- [x] `"stop last (job/ticket)"`
- [x] `"start all"`
- [x] `"stop all"`
- [x] `"done all"` close all issue of current list
- [ ] `"start <job>"` update status of job to <in progress> ➡️  https://github.com/botstory/todo-bot/issues/82
- [ ] `"start <list>"`, `"switch to <list>"`, `"jump to <list>"` make list active
- [ ] `"stop <job>"` update status of job to <open> ➡️  https://github.com/botstory/todo-bot/issues/82
- [ ] `"done <job>"` close job ➡️  https://github.com/botstory/todo-bot/issues/82

# [D]elete
- [x] `"remove last"` (`do you really want to remove <> job?`)
- [x] `"remove all (jobs/tickets)"` (`do you really want to remove all your jobs?`)
- [x] `"remove <job>"`, `"forget about <job>"`, `"kill <job>"` remove job from list
- [x] `"remove <list>"`, `"forget about <list name>"`, `"kill <list>"` remove list of jobs
- [x] remove in context of task details, by postback message
- [ ] `"remove all (my) lists"` (`do you really want to remove all your lists?`)
- [ ] advanced: if we don't know what to remove ask by quick answer: <is it new task?>

# Other
- [ ]  `"?"`, `"help"`, `"what can I do here?"` show help ➡️  https://github.com/botstory/todo-bot/issues/77
- [ ] ":thumbsup:" I like you too! ➡️  https://github.com/botstory/todo-bot/issues/78
