### ISSUE TITLE
list of jobs

### ISSUE THREAD

**Issue by hyzhak** [botstory/todo-bot#5]
# TODO

- [x] last the first
- [ ] options (?)
- [ ] `...` at the end/begin of page of list if it is not the edge
- [ ] render empty list 
`<nothing>. you could send any message to create new job todo.`

Prototype:

My Grocery List

...
:white_medium_square: beacon
:white_medium_square: eggs
:white_check_mark: milk
:white_check_mark: tomatoes
...

(all lists) (more) (done: beacon) (done: others)

(done: other)->
(done: eggs) (done: other) (done all jobs)
