### ISSUE TITLE
share todo lists

### ISSUE THREAD

**Issue by hyzhak** [botstory/todo-bot#99]
- [ ] share link to the todo list 
- [ ] invite new user by list url
- [ ] inform owner then collaborator receive todo list
- [ ] other user could read, write, edit list (and/or). By default only start/stop/done
- [ ] send update to an owner when state was changes
- [ ] send update to a collaborator when list we
